#!/usr/bin/env python3
"""Download the corpus into corpus/ from each document's ORIGINAL source.

What to download comes from [[documents]] in corpus.toml (entries with a `url`). The files are not
committed to the repo (see .gitignore); corpus/SOURCES.md, which this script writes from the same
config, records where each came from and on what terms. Takes no parameters. Files that already
exist are skipped, so it is safe to re-run. Needs Python 3.11+ (tomllib); standard library only.
"""
import sys
import time
import urllib.request
from pathlib import Path

try:
    import tomllib
except ModuleNotFoundError:
    sys.exit("Python 3.11 or newer is needed (for tomllib).")

ROOT = Path(__file__).resolve().parent.parent
CORPUS = ROOT / "corpus"
CONFIG = ROOT / "corpus.toml"
# Some publishers (aemo.com.au for one) reject unknown clients, so identify as a browser-compatible agent.
USER_AGENT = "Mozilla/5.0 (compatible; agentic-demo-docs/1.0; personal demo)"

KIND_BY_SUFFIX = {".pdf": "pdf", ".html": "html", ".htm": "html"}  # anything else is plain text
MIN_BYTES = {"text": 20_000, "html": 50_000, "pdf": 50_000}


def kind_of(name: str) -> str:
    return KIND_BY_SUFFIX.get(Path(name).suffix.lower(), "text")


def looks_right(data: bytes, kind: str) -> bool:
    """Guard against bot-check or error pages saved under a .pdf/.txt name."""
    if len(data) < MIN_BYTES[kind]:
        return False
    if kind == "pdf":
        return data.startswith(b"%PDF")
    head = data[:2000].lower()
    is_html = b"<!doctype html" in head or b"<html" in head
    return is_html if kind == "html" else not is_html


def fetch(url: str, headers: dict) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT, **headers})
    with urllib.request.urlopen(req, timeout=120) as resp:
        return resp.read()


def write_sources(config: dict) -> None:
    """corpus/SOURCES.md: the attribution record, generated so it can not drift from the config."""
    docs = [d for d in config.get("documents", []) if d.get("url")]
    lines = [
        f"# Corpus sources and terms: {config.get('corpus', {}).get('name', 'documents')}",
        "",
        "Generated by `scripts/download_corpus.py` from `corpus.toml`; edit that, not this file.",
        "The documents themselves are **not stored in this repository**: `make ingest` downloads each one",
        "from its original publisher into this folder (git-ignored).",
        "",
    ]
    notes = config.get("corpus", {}).get("notes", "").strip()
    if notes:
        lines += [notes, ""]
    lines += ["| File | Source | Terms |", "|---|---|---|"]
    for d in docs:
        lines.append(f"| `{d['file']}` | [{d.get('title', d['file'])}]({d['url']}) | {d.get('terms', '')} |")
    lines += ["", "Using your own documents: see the top-level README.", ""]
    CORPUS.mkdir(exist_ok=True)
    (CORPUS / "SOURCES.md").write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    if not CONFIG.exists():
        sys.exit(f"{CONFIG} not found")
    config = tomllib.loads(CONFIG.read_text(encoding="utf-8"))
    docs = [d for d in config.get("documents", []) if d.get("url")]
    if not docs:
        print("corpus.toml lists no documents with a url: nothing to download (add your own files to corpus/).")
        return 0

    CORPUS.mkdir(exist_ok=True)
    failed = 0
    for i, doc in enumerate(docs):
        name, url = doc["file"], doc["url"]
        target = CORPUS / name
        if target.exists():
            print(f"skip     {name} (already downloaded)")
            continue
        if i:
            time.sleep(1)  # be polite to the hosts
        try:
            kind = doc.get("kind") or kind_of(name)
            data = fetch(url, doc.get("headers", {}))
            if not looks_right(data, kind):
                raise ValueError(f"unexpected content ({len(data)} bytes, not a valid {kind})")
            tmp = target.with_suffix(target.suffix + ".part")
            tmp.write_bytes(data)
            tmp.replace(target)
            print(f"ok       {name} ({len(data) / 1e6:.1f} MB)  <- {url}")
        except Exception as e:  # keep going so one broken link doesn't block the rest
            failed += 1
            print(f"FAILED   {name}: {e}\n         {url}", file=sys.stderr)

    write_sources(config)
    print(f"\n{len(docs) - failed}/{len(docs)} documents available in {CORPUS} (sources recorded in SOURCES.md)")
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
